getwd()
setwd("/Users/advaitiyer/Desktop")
df = read.csv("Time-series.csv")
df
tsData = ts(df,start = c(2000), end = c(2016), frequency = 1)
plot.ts(tsData)

library(zoo)
library(ggplot2)
autoplot(zoo(t(tsData)), facets = NULL)

install.packages("mvtsplot")
library(mvtsplot)

mvtsplot(tsData[,2:51], group = NULL, xtime = NULL, norm = c("internal", "global"),
         levels = 3, smooth.df = NULL, margin = TRUE, sort = NULL,
         main = "", palette = "PRGn", rowstat = "median", xlim,
         bottom.ylim = NULL, right.xlim = NULL, gcol = 1)



p1 = autoplot(tsData[,2:4]) + xlab("Year") + ylab("Freedom index")
p2 = autoplot(tsData[,5:7]) + xlab("Year") + ylab("Freedom index")
p3 = autoplot(tsData[,8:10]) + xlab("Year") + ylab("Freedom index")
p4 = autoplot(tsData[,11:13]) + xlab("Year") + ylab("Freedom index")
p5 = autoplot(tsData[,14:16]) + xlab("Year") + ylab("Freedom index")
p5 = autoplot(tsData[,17:19]) + xlab("Year") + ylab("Freedom index")
p6 = autoplot(tsData[,20:22]) + xlab("Year") + ylab("Freedom index")
p7 = autoplot(tsData[,23:25]) + xlab("Year") + ylab("Freedom index")
p8 = autoplot(tsData[,26:28]) + xlab("Year") + ylab("Freedom index")
p9 = autoplot(tsData[,29:31]) + xlab("Year") + ylab("Freedom index")
p10 = autoplot(tsData[,32:34]) + xlab("Year") + ylab("Freedom index")
p11 = autoplot(tsData[,35:37]) + xlab("Year") + ylab("Freedom index")
p12 = autoplot(tsData[,38:40]) + xlab("Year") + ylab("Freedom index")
p13 = autoplot(tsData[,41:43]) + xlab("Year") + ylab("Freedom index")
p14 = autoplot(tsData[,44:46]) + xlab("Year") + ylab("Freedom index")
p15 = autoplot(tsData[,47:49]) + xlab("Year") + ylab("Freedom index")
p16 = autoplot(tsData[,50:51]) + xlab("Year") + ylab("Freedom index")

#install.packages("ggpubr")
library(ggpubr)
ggarrange(p1, p2, p3, p4)
ggarrange(p5, p6, p7, p8)
ggarrange(p9, p10, p11, p12)
ggarrange(p13, p14, p15, p16)

checkresiduals(snaive(tsData[,2]))
checkresiduals(snaive(tsData[,3]))
checkresiduals(snaive(tsData[,4]))
checkresiduals(snaive(tsData[,5]))
checkresiduals(snaive(tsData[,6]))
checkresiduals(snaive(tsData[,7]))
checkresiduals(snaive(tsData[,8]))
checkresiduals(snaive(tsData[,9]))
checkresiduals(snaive(tsData[,10]))
checkresiduals(snaive(tsData[,11]))
checkresiduals(snaive(tsData[,12]))
checkresiduals(snaive(tsData[,13]))
checkresiduals(snaive(tsData[,14]))
checkresiduals(snaive(tsData[,15]))
checkresiduals(snaive(tsData[,16]))

alabama = forecast(nnetar(tsData[,2],lambda = NULL), h=3)
alabama
autoplot(alabama)

alaska = forecast(nnetar(tsData[,3],lambda = NULL), h=3)
autoplot(alaska)

arizona = forecast(nnetar(tsData[,4],lambda = NULL), h=3)
autoplot(arizona)

arkansas = forecast(nnetar(tsData[,5],lambda = NULL), h=3)
autoplot(arkansas)

california = forecast(nnetar(tsData[,6],lambda = NULL), h=3)
colorado = forecast(nnetar(tsData[,7],lambda = NULL), h=3)
connecticut = forecast(nnetar(tsData[,8],lambda = NULL), h=3)
delaware = forecast(nnetar(tsData[,9],lambda = NULL), h=3)
florida = forecast(nnetar(tsData[,10],lambda = NULL), h=3)
georgia = forecast(nnetar(tsData[,11],lambda = NULL), h=3)
hawaii = forecast(nnetar(tsData[,12],lambda = NULL), h=3)
idaho = forecast(nnetar(tsData[,13],lambda = NULL), h=3)
illinois = forecast(nnetar(tsData[,14],lambda = NULL), h=3)
indiana = forecast(nnetar(tsData[,15],lambda = NULL), h=3)
iowa = forecast(nnetar(tsData[,16],lambda = NULL), h=3)
kansas = forecast(nnetar(tsData[,17],lambda = NULL), h=3)
kentucky = forecast(nnetar(tsData[,18],lambda = NULL), h=3)
louisiana = forecast(nnetar(tsData[,19],lambda = NULL), h=3)
maine = forecast(nnetar(tsData[,20],lambda = NULL), h=3)
maryland = forecast(nnetar(tsData[,21],lambda = NULL), h=3)
massachussetts = forecast(nnetar(tsData[,22],lambda = NULL), h=3)
michigan = forecast(nnetar(tsData[,23],lambda = NULL), h=3)
minnesota = forecast(nnetar(tsData[,24],lambda = NULL), h=3)
mississippi = forecast(nnetar(tsData[,25],lambda = NULL), h=3)
missouri = forecast(nnetar(tsData[,26],lambda = NULL), h=3)
montana = forecast(nnetar(tsData[,27],lambda = NULL), h=3)
nebraska = forecast(nnetar(tsData[,28],lambda = NULL), h=3)
nevada = forecast(nnetar(tsData[,29],lambda = NULL), h=3)
newhampshire = forecast(nnetar(tsData[,30],lambda = NULL), h=3)
newjersey = forecast(nnetar(tsData[,31],lambda = NULL), h=3)
newmexico = forecast(nnetar(tsData[,32],lambda = NULL), h=3)
newyork = forecast(nnetar(tsData[,33],lambda = NULL), h=3)
northcarolina = forecast(nnetar(tsData[,34],lambda = NULL), h=3)
northdakota = forecast(nnetar(tsData[,35],lambda = NULL), h=3)
ohio = forecast(nnetar(tsData[,36],lambda = NULL), h=3)
oklahoma = forecast(nnetar(tsData[,37],lambda = NULL), h=3)
oregon = forecast(nnetar(tsData[,38],lambda = NULL), h=3)
pennsylvania = forecast(nnetar(tsData[,39],lambda = NULL), h=3)
rhodeisland = forecast(nnetar(tsData[,40],lambda = NULL), h=3)
southcarolina = forecast(nnetar(tsData[,41],lambda = NULL), h=3)
southdakota = forecast(nnetar(tsData[,42],lambda = NULL), h=3)
tennesse = forecast(nnetar(tsData[,43],lambda = NULL), h=3)
texas = forecast(nnetar(tsData[,44],lambda = NULL), h=3)
utah = forecast(nnetar(tsData[,45],lambda = NULL), h=3)
vermont = forecast(nnetar(tsData[,46],lambda = NULL), h=3)
virginia = forecast(nnetar(tsData[,47],lambda = NULL), h=3)
washington = forecast(nnetar(tsData[,48],lambda = NULL), h=3)
westvirginia = forecast(nnetar(tsData[,49],lambda = NULL), h=3)
wisconsin = forecast(nnetar(tsData[,50],lambda = NULL), h=3)
wyoming = forecast(nnetar(tsData[,51],lambda = NULL), h=3)


