getwd()
setwd("/Users/advaitiyer/Desktop/Sambhavi/SOM")
df = read.csv("obese-timeseries.csv")
df
tsData = ts(df,start = c(1975), end = c(2016), frequency = 1)
# plot.ts(tsData)

library(zoo)
library(ggplot2)
#autoplot(zoo(t(tsData)), facets = NULL)

install.packages("mvtsplot")
library(mvtsplot)

mvtsplot(tsData[,2:199], group = NULL, xtime = NULL, norm = c("internal", "global"),
         levels = 3, smooth.df = NULL, margin = TRUE, sort = NULL,
         main = "", palette = "PRGn", rowstat = "median", xlim,
         bottom.ylim = NULL, right.xlim = NULL, gcol = 1)

library(forecast)

colnames(df[,2:199])

afghanistan = forecast(nnetar(tsData[,2],lambda = NULL), h=3)
afghanistan
autoplot(afghanistan)

afghanistan=forecast(nnetar(tsData[,2],lambda = NULL), h=3)
africa=forecast(nnetar(tsData[,3],lambda = NULL), h=3)
albania=forecast(nnetar(tsData[,4],lambda = NULL), h=3)
algeria=forecast(nnetar(tsData[,5],lambda = NULL), h=3)
americas=forecast(nnetar(tsData[,6],lambda = NULL), h=3)
andorra=forecast(nnetar(tsData[,7],lambda = NULL), h=3)
angolia=forecast(nnetar(tsData[,8],lambda = NULL), h=3)
antigua_and_barbuda=forecast(nnetar(tsData[,9],lambda = NULL), h=3)
argentina=forecast(nnetar(tsData[,10],lambda = NULL), h=3)
armenia=forecast(nnetar(tsData[,11],lambda = NULL), h=3)
australia=forecast(nnetar(tsData[,12],lambda = NULL), h=3)
austria=forecast(nnetar(tsData[,13],lambda = NULL), h=3)
azerbaijan=forecast(nnetar(tsData[,14],lambda = NULL), h=3)
bahamas=forecast(nnetar(tsData[,15],lambda = NULL), h=3)
bahrain=forecast(nnetar(tsData[,16],lambda = NULL), h=3)
bangladesh=forecast(nnetar(tsData[,17],lambda = NULL), h=3)
barbados=forecast(nnetar(tsData[,18],lambda = NULL), h=3)
belarus=forecast(nnetar(tsData[,19],lambda = NULL), h=3)
maine = forecast(nnetar(tsData[,20],lambda = NULL), h=3)
maryland = forecast(nnetar(tsData[,21],lambda = NULL), h=3)
massachussetts = forecast(nnetar(tsData[,22],lambda = NULL), h=3)
michigan = forecast(nnetar(tsData[,23],lambda = NULL), h=3)
minnesota = forecast(nnetar(tsData[,24],lambda = NULL), h=3)
mississippi = forecast(nnetar(tsData[,25],lambda = NULL), h=3)
missouri = forecast(nnetar(tsData[,26],lambda = NULL), h=3)
montana = forecast(nnetar(tsData[,27],lambda = NULL), h=3)
nebraska = forecast(nnetar(tsData[,28],lambda = NULL), h=3)
nevada = forecast(nnetar(tsData[,29],lambda = NULL), h=3)
newhampshire = forecast(nnetar(tsData[,30],lambda = NULL), h=3)
newjersey = forecast(nnetar(tsData[,31],lambda = NULL), h=3)
newmexico = forecast(nnetar(tsData[,32],lambda = NULL), h=3)
newyork = forecast(nnetar(tsData[,33],lambda = NULL), h=3)
northcarolina = forecast(nnetar(tsData[,34],lambda = NULL), h=3)
northdakota = forecast(nnetar(tsData[,35],lambda = NULL), h=3)
ohio = forecast(nnetar(tsData[,36],lambda = NULL), h=3)
oklahoma = forecast(nnetar(tsData[,37],lambda = NULL), h=3)
oregon = forecast(nnetar(tsData[,38],lambda = NULL), h=3)
pennsylvania = forecast(nnetar(tsData[,39],lambda = NULL), h=3)
rhodeisland = forecast(nnetar(tsData[,40],lambda = NULL), h=3)
southcarolina = forecast(nnetar(tsData[,41],lambda = NULL), h=3)
southdakota = forecast(nnetar(tsData[,42],lambda = NULL), h=3)
tennesse = forecast(nnetar(tsData[,43],lambda = NULL), h=3)
texas = forecast(nnetar(tsData[,44],lambda = NULL), h=3)
utah = forecast(nnetar(tsData[,45],lambda = NULL), h=3)
vermont = forecast(nnetar(tsData[,46],lambda = NULL), h=3)
virginia = forecast(nnetar(tsData[,47],lambda = NULL), h=3)
washington = forecast(nnetar(tsData[,48],lambda = NULL), h=3)
westvirginia = forecast(nnetar(tsData[,49],lambda = NULL), h=3)
wisconsin = forecast(nnetar(tsData[,50],lambda = NULL), h=3)
wyoming = forecast(nnetar(tsData[,51],lambda = NULL), h=3)


